#!/bin/bash

# Run make file if r flag is typed
if [[ "$1" = "r" ]]; then
	make 
fi

# If there were no compilation errors, run the program
if [[ $? -eq 0 ]]; then
        ./objects/dll
fi

# If seg fault occurs, start gdb if flag y is typed
if [[ $? -eq 139 ]]; then
	if [ "$1" = "y" ]; then
		gdb ./objects/dll
	fi
fi
